import Head from 'next/head'
import Image from 'next/image'
import Hero from '../components/Hero'
import styles from '../styles/Layout.module.scss'

function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WPT-Cricket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        

        <Hero/>
      </main>

    
    </div>
  )
}


export default Home