import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

function Records() {
  return (
    <div className={styles.container}>
      <Head>
        <title>WPT-Cricket</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Records
        </h1>


        <ul className={styles.recordlist}>
          <li className={styles.record}>
            <Image 
            src="/images/g1.jpg"
            width="550px"
            height="550px"
            layout="fixed" 
            alt="" />
            <h2>HIGHEST TOTAL INNING</h2>
          </li>
          <li className={styles.record}>
            <Image 
            src="/images/g2.jpg"
            width="550px"
            height="550px"
            layout="fixed" 
            alt="" />
            <h2>MOST CAREER RUNS</h2>
          </li>
          <li className={styles.record}>
            <Image 
            src="/images/g3.jpg"
            width="550px"
            height="550px"
            layout="fixed" 
            alt="" />
            <h2>MOST CAREER WICKETS</h2>
          </li>
          <li className={styles.record}>
            <Image 
            src="/images/g4.jpg"
            width="550px"
            height="550px"
            layout="fixed" 
            alt="" />
            <h2>HIGHEST PARTNERSHIP</h2>
          </li>
          <li className={styles.record}>
            <Image 
            src="/images/g5.jpg"
            width="550px"
            height="550px"
            layout="fixed" 
            alt="" />
            <h2>THIRD MOST CAREER RUNS</h2>
          </li>
          <li className={styles.record}>
            <Image 
            src="/images/g6.jpg"
            width="550px"
            height="550px"
            layout="fixed" 
            alt="" />
            <h2>HAT-TRICK</h2>
          </li>

          </ul>

        
      </main>

    
    </div>
  )
}


export default Records