import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Layout.module.scss'

export default function Upcoming() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Upcoming</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        Upcoming
        </h1>

        
      </main>

    
    </div>
  )
}